import os
import csv
from typing import List
import pandas as pd
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from core.bom_model import BOMItem

class BOMExporter:
    """BOM 데이터를 Excel 및 CSV 파일로 내보내는 유틸리티"""

    @staticmethod
    def export_to_excel(items: List[BOMItem], file_path: str, assembly_title: str = "BOM") -> bool:
        """전문적인 스타일이 적용된 Excel(.xlsx) 파일 생성"""
        try:
            # 1. DataFrame 변환
            data = [item.to_dict() for item in items]
            df = pd.DataFrame(data)

            # 2. ExcelWriter 생성 (openpyxl 엔진)
            with pd.ExcelWriter(file_path, engine="openpyxl") as writer:
                df.to_excel(writer, sheet_name="BOM_List", index=False, startrow=3)

                workbook = writer.book
                worksheet = writer.sheets["BOM_List"]

                # 제목 행 스타일링
                total_cols = len(df.columns)
                last_col_letter = get_column_letter(total_cols)
                worksheet.merge_cells(f"A1:{last_col_letter}1")
                title_cell = worksheet["A1"]
                title_cell.value = f"BILL OF MATERIALS (BOM) - {assembly_title}"
                title_cell.font = Font(name="Segoe UI", size=16, bold=True, color="1F2937")
                title_cell.alignment = Alignment(horizontal="center", vertical="center")
                worksheet.row_dimensions[1].height = 40

                # 서브 타이틀 (작성일시/정보)
                worksheet.merge_cells(f"A2:{last_col_letter}2")
                sub_cell = worksheet["A2"]
                import datetime
                sub_cell.value = f"Generated by SolidWorks BOM Manager V0.0 | Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Total Unique Items: {len(items)}"
                sub_cell.font = Font(name="Segoe UI", size=9, italic=True, color="4B5563")
                sub_cell.alignment = Alignment(horizontal="left", vertical="center")
                worksheet.row_dimensions[2].height = 20

                # 테이블 헤더 스타일 (Row 4)
                header_fill = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid") # Dark Blue
                header_font = Font(name="Segoe UI", size=10, bold=True, color="FFFFFF")
                header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

                thin_border = Border(
                    left=Side(style='thin', color='D1D5DB'),
                    right=Side(style='thin', color='D1D5DB'),
                    top=Side(style='thin', color='D1D5DB'),
                    bottom=Side(style='thin', color='D1D5DB')
                )

                worksheet.row_dimensions[4].height = 28

                for col_idx in range(1, len(df.columns) + 1):
                    cell = worksheet.cell(row=4, column=col_idx)
                    cell.fill = header_fill
                    cell.font = header_font
                    cell.alignment = header_alignment
                    cell.border = thin_border

                # 데이터 행 스타일
                alt_fill = PatternFill(start_color="F9FAFB", end_color="F9FAFB", fill_type="solid")
                white_fill = PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")
                data_font = Font(name="Segoe UI", size=9)

                for r_idx in range(5, 5 + len(df)):
                    worksheet.row_dimensions[r_idx].height = 22
                    row_fill = alt_fill if r_idx % 2 == 0 else white_fill
                    for c_idx in range(1, len(df.columns) + 1):
                        cell = worksheet.cell(row=r_idx, column=c_idx)
                        cell.font = data_font
                        cell.border = thin_border
                        cell.fill = row_fill

                        # 열별 정렬
                        col_name = df.columns[c_idx - 1]
                        if col_name in ["No", "Common Part", "Q'TY", "Configuration"]:
                            cell.alignment = Alignment(horizontal="center", vertical="center")
                        elif col_name in ["Material"]:
                            cell.alignment = Alignment(horizontal="center", vertical="center")
                        else:
                            cell.alignment = Alignment(horizontal="left", vertical="center")

                # 열 너비 자동 조정
                for col in worksheet.columns:
                    col_letter = get_column_letter(col[0].column)
                    max_len = 0
                    for cell in col:
                        if cell.row < 4:
                            continue
                        val = str(cell.value or "")
                        max_len = max(max_len, len(val.encode('utf-8')))
                    worksheet.column_dimensions[col_letter].width = max(max_len * 1.1 + 4, 12)

            return True
        except Exception as e:
            print(f"Excel 내보내기 실패: {e}")
            raise e

    @staticmethod
    def export_to_csv(items: List[BOMItem], file_path: str) -> bool:
        """한글이 깨지지 않는 UTF-8 with BOM(utf-8-sig) CSV 파일 생성"""
        try:
            fieldnames = ["No", "Common Part", "Name of Part", "Material", "Q'TY", "Rev.", "REMARK"]
            with open(file_path, mode="w", newline="", encoding="utf-8-sig") as f:
                writer = csv.DictWriter(f, fieldnames=fieldnames)
                writer.writeheader()
                for item in items:
                    writer.writerow(item.to_dict())
            return True
        except Exception as e:
            print(f"CSV 내보내기 실패: {e}")
            raise e
